# Makefile
CC = gcc
CFLAGS = -Wall -g
SORT_OBJ = sort.o
SEARCH_OBJ = search.o
TREE_OBJ = tree.o
LINKLIST_OBJ = linklist.o
QUEUE_OBJ = queue_stack.o
SORT_TARGET = sort
SEARCH_TARGET = search
TREE_TARGET = tree
LINKLIST_TARGET = linklist
QUEUE_TARGET = queue_stack

all: $(SORT_TARGET) $(SEARCH_TARGET) $(TREE_TARGET) $(LINKLIST_TARGET) ${QUEUE_TARGET}

$(SORT_TARGET): $(SORT_OBJ)
	$(CC) -o $(SORT_TARGET) $(SORT_OBJ)

$(SEARCH_TARGET): $(SEARCH_OBJ)
	$(CC) -o $(SEARCH_TARGET) $(SEARCH_OBJ)

$(TREE_TARGET): $(TREE_OBJ)
	$(CC) -o $(TREE_TARGET) $(TREE_OBJ)

$(LINKLIST_TARGET): $(LINKLIST_OBJ)
	$(CC) -o $(LINKLIST_TARGET) $(LINKLIST_OBJ)

$(QUEUE_TARGET): $(QUEUE_OBJ)
	$(CC) -o $(QUEUE_TARGET) $(QUEUE_OBJ)

%.o: %.c
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f $(SORT_OBJ) $(SEARCH_OBJ) $(TREE_OBJ) ${LINKLIST_OBJ} $(TREE_TARGET) $(LINKLIST_TARGET) $(SORT_TARGET) $(SEARCH_TARGET) $(QUEUE_TARGET) $(QUEUE_OBJ)

.PHONY: all clean
